version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
    commands:
      - echo Installing Google Chrome...
      - wget https://dl.google.com/linux/direct/google-chrome-stable_current_x86_64.rpm
      - yum localinstall -y google-chrome-stable_current_x86_64.rpm
      - google-chrome --version

  pre_build:
    commands:
      - echo Cleaning project...
      - mvn clean

  build:
    commands:
      - echo Running Cucumber Tests...
      - mvn test

artifacts:
  files:
    - target/**/*